name: common_setup
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.6
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 900
    - family: GE_Flow_Regular
      fonts:
        - asset: assets/fonts/GE_Flow_Regular/GE_Flow_Regular.ttf
          weight: 300
        - asset: assets/fonts/GE_Flow_Regular/GE_Flow_Regular.ttf
          weight: 900
        - asset: assets/fonts/GE_Flow_Regular/GE_Flow_Regular.ttf
          weight: 700
        - asset: assets/fonts/GE_Flow_Regular/GE_Flow_Regular.ttf
          weight: 500
